/**
 * src/pages/api/operations/cart/add-product-to-cart.ts 
 * Adds products to cart via AddToCart mutation
 * NOTES Probably don't need this, not sure yet. I think we can just handle
 * everything in the hook generated by graphql-codegen
 * @author Myles Berueda <MylesWritesCode>
 */
import { getShopifyData } from '@utils/getShopifyData';
import { AddToCartDocument } from '@generated/schema';
import type { LineItem } from '@type/cart.type';

import { SHOPIFY_API_URL, SHOPIFY_COOKIE_ID } from '@/const';

export async function addProductToCart(cartInput: LineItem) {

}
